//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@interface SpringBoard : UIApplication

- (void)applicationDidFinishLaunching:(id)arg1;
- (void)_menuButtonDown:(struct __IOHIDEvent *)arg1;
- (void)_menuButtonUp:(struct __IOHIDEvent *)arg1;
- (_Bool)_volumeChanged:(struct __IOHIDEvent *)arg1;

@end

